export const CHAT_MODES = {
  general: {
    label: "General",
    description: "Everyday conversations",
    kind: "text",
    system: "You are Nova, a helpful AI assistant.",
    web: false,
    accent: "text-blue-600",
  },
  coding: {
    label: "Coding",
    description: "Write and debug code",
    kind: "text",
    system: "You are a coding expert. Help with programming tasks.",
    web: false,
    accent: "text-violet-600",
  },
  reasoning: {
    label: "Reasoning",
    description: "Complex problem solving",
    kind: "text",
    system: "You are a reasoning expert. Think step by step.",
    web: false,
    accent: "text-emerald-600",
  },
  writing: {
    label: "Writing",
    description: "Draft and edit content",
    kind: "text",
    system: "You are a writing expert. Help with content creation.",
    web: false,
    accent: "text-sky-600",
  },
  image: {
    label: "Image",
    description: "Generate images",
    kind: "image",
    system: "You are an image generation assistant.",
    web: false,
    accent: "text-rose-600",
  },
  voice: {
    label: "Voice",
    description: "Voice conversations",
    kind: "voice",
    system: "You are a voice assistant. Respond conversationally.",
    web: false,
    accent: "text-fuchsia-600",
  },
};
